name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer
        run: |
          pip install --upgrade buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y python3-dev libffi-dev libssl-dev build-essential zip libz-dev

      - name: Build APK
        run: |
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MonAppli-BECP
          path: bin/*.apk
