name: go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: buildozer android debug
      - uses: actions/upload-artifact@v3
        with:
          name: Mon-IA-APK
          path: bin/*.apk
